name: 🚀 New feature proposal
description: Propose a new feature to be added to `elysia-realworld-example-app`
labels: ['enhancement: pending triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: textarea
    id: feature-description
    attributes:
      label: Clear and concise description of the problem
      description: 'As a developer using `elysia-realworld-example-app` I want [goal / wish] so that [benefit]. If you intend to submit a PR for this issue, tell us in the description. Thanks!'
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: We could implement it as ...
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the FR, please make sure you do the following
      options:
        - label: Read the [Contributing Guide](https://github.com/agnyz/elysia-realworld-example-app/blob/main/CONTRIBUTING.md).
          required: true
        - label: Read the `README.md`.
          required: true
        - label: Check that there isn't already an issue that requests the same feature.
          required: true